---
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /health
        healthCheckInterval: 15s
        

hello:
  world: someDummyValue
        
endpoints:
  health:
    sensitive: false        
