spring:
  cloud:
    consul:
      host: 54.84.108.202
      port: 8500
      discovery:
        healthCheckPath: /health
        healthCheckInterval: 15s
    config:
      env: dev # optional
      profile: dev
      label: master # optional
      uri: http://54.84.108.202:8888/ # optionalendpoints:
  health:
    sensitive: false
hello:
  world: changed-coe-web-dev-profile**
